### ISSUE TITLE
Function Limitation Review

### ISSUE THREAD

**Issue by Haxrox** [WorldofKerry/Python2Verilog#144]
Reviewing: https://github.com/WorldofKerry/Python2Verilog/blob/6ca0a18ac1182d15249d682588c311fd96b8bfbb/docs/for_loop_limitation.md

A few questions:
1. Is the generated FSM for the caller?
2. Why can't `Work then Loop` be under the `Loop` state?
3. Where are your function calls? 
4. Are the `done`, `valid` signals from the callee?
5. For the flag solution, what's the difference between `is_done` and `done`?

**Comment by WorldofKerry** [comment]
Changes in #145
